export {
  FABER_ORANGE,
  FABER_ORANGE_HOVER,
  cabinetPageClassName as clientPageClassName,
  cabinetPageNarrowClassName as clientPageNarrowClassName,
  cabinetCardCls as clientCardCls,
  cabinetCardStaticCls as clientCardStaticCls,
  cabinetIconWrapCls as clientIconWrapCls,
  cabinetTextTitle as clientTextTitle,
  cabinetTextBody as clientTextBody,
  cabinetTextMuted as clientTextMuted,
  cabinetSectionTitleCls as clientSectionTitleCls,
  cabinetInsetPanelCls as clientInsetPanelCls,
  cabinetPrimaryBtnCls as clientPrimaryBtnCls,
  cabinetOutlineBtnCls as clientOutlineBtnCls,
  cabinetLinkCls as clientLinkCls,
  cabinetBadgeCls as clientBadgeCls,
  cabinetFilterPillCls as clientFilterPillCls,
  cabinetFormLabelCls as clientFormLabelCls,
  cabinetInputCls as clientInputCls,
  cabinetTextareaCls as clientTextareaCls,
  cabinetSelectTriggerCls as clientSelectTriggerCls,
  cabinetFormCardCls as clientFormCardCls,
  cabinetChoiceCardCls as clientChoiceCardCls,
} from '@/lib/cabinetStyles';
