export {
  FABER_ORANGE,
  FABER_ORANGE_HOVER,
  cabinetPageClassName as masterPageClassName,
  cabinetPageWideClassName as masterPageWideClassName,
  cabinetPageNarrowClassName as masterPageNarrowClassName,
  cabinetPageMediumClassName as masterPageMediumClassName,
  cabinetPageBookingsClassName as masterPageBookingsClassName,
  cabinetCardCls as masterCardCls,
  cabinetCardStaticCls as masterCardStaticCls,
  cabinetIconWrapCls as masterIconWrapCls,
  cabinetTextTitle as masterTextTitle,
  cabinetTextBody as masterTextBody,
  cabinetTextMuted as masterTextMuted,
  cabinetSectionTitleCls as masterSectionTitleCls,
  cabinetInsetPanelCls as masterInsetPanelCls,
  cabinetPrimaryBtnCls as masterPrimaryBtnCls,
  cabinetOutlineBtnCls as masterOutlineBtnCls,
  cabinetLinkCls as masterLinkCls,
  cabinetBadgeCls as masterBadgeCls,
  cabinetFilterPillCls as masterFilterPillCls,
  cabinetFormLabelCls as masterFormLabelCls,
  cabinetInputCls as masterInputCls,
  cabinetTextareaCls as masterTextareaCls,
  cabinetSelectTriggerCls as masterSelectTriggerCls,
  cabinetFormCardCls as masterFormCardCls,
  cabinetDialogContentCls as masterDialogContentCls,
  cabinetChoiceCardCls as masterChoiceCardCls,
} from '@/lib/cabinetStyles';
