/**
 * Prisma NotificationCategory — те же строки, что в schema.prisma / API.
 * Использовать вместо литералов 'NEW_LEAD', 'ADMIN_NEW_LEAD', …
 */
export const NOTIFICATION_CATEGORY = {
  NEW_LEAD: 'NEW_LEAD',
  LEAD_STATUS_UPDATED: 'LEAD_STATUS_UPDATED',
  NEW_REVIEW: 'NEW_REVIEW',
  NEW_CHAT_MESSAGE: 'NEW_CHAT_MESSAGE',
  SUBSCRIPTION_EXPIRING: 'SUBSCRIPTION_EXPIRING',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  VERIFICATION_APPROVED: 'VERIFICATION_APPROVED',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
  ADMIN_NEW_VERIFICATION: 'ADMIN_NEW_VERIFICATION',
  ADMIN_NEW_REPORT: 'ADMIN_NEW_REPORT',
  ADMIN_NEW_USER: 'ADMIN_NEW_USER',
  ADMIN_NEW_MASTER: 'ADMIN_NEW_MASTER',
  ADMIN_SYSTEM_ALERT: 'ADMIN_SYSTEM_ALERT',
  ADMIN_NEW_LEAD: 'ADMIN_NEW_LEAD',
  ADMIN_NEW_REVIEW: 'ADMIN_NEW_REVIEW',
  ADMIN_NEW_PAYMENT: 'ADMIN_NEW_PAYMENT',
  LEAD_SENT: 'LEAD_SENT',
  LEAD_CLOSE_REQUESTED: 'LEAD_CLOSE_REQUESTED',
  MASTER_RESPONDED: 'MASTER_RESPONDED',
  MASTER_AVAILABLE: 'MASTER_AVAILABLE',
  BOOKING_PENDING: 'BOOKING_PENDING',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_REMINDER: 'BOOKING_REMINDER',
  NEW_PROMOTION: 'NEW_PROMOTION',
  PROMOTION_STARTED: 'PROMOTION_STARTED',
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
  SYSTEM_UPDATE: 'SYSTEM_UPDATE',
  JOB_APPLICATION_RECEIVED: 'JOB_APPLICATION_RECEIVED',
  JOB_MASTER_SELECTED: 'JOB_MASTER_SELECTED',
  JOB_STATUS_CHANGED: 'JOB_STATUS_CHANGED',
} as const;

export type NotificationCategory =
  (typeof NOTIFICATION_CATEGORY)[keyof typeof NOTIFICATION_CATEGORY];
