/**
 * Prisma NotificationCategory (uppercase) → фронтовый event type (snake_case).
 * Единый источник для WebSocket и REST GET /notifications.
 */
import { NOTIFICATION_CATEGORY } from './notificationCategory';
import type { NotificationEventType } from './notificationEventType';
import { NOTIFICATION_EVENT_TYPE } from './notificationEventType';

export const NOTIFICATION_CATEGORY_TO_EVENT_TYPE: Record<
  string,
  NotificationEventType
> = {
  [NOTIFICATION_CATEGORY.NEW_LEAD]: NOTIFICATION_EVENT_TYPE.new_lead,
  [NOTIFICATION_CATEGORY.NEW_REVIEW]: NOTIFICATION_EVENT_TYPE.new_review,
  [NOTIFICATION_CATEGORY.LEAD_STATUS_UPDATED]:
    NOTIFICATION_EVENT_TYPE.lead_status_updated,
  [NOTIFICATION_CATEGORY.LEAD_SENT]: NOTIFICATION_EVENT_TYPE.lead_sent,
  [NOTIFICATION_CATEGORY.LEAD_CLOSE_REQUESTED]:
    NOTIFICATION_EVENT_TYPE.lead_close_requested,
  [NOTIFICATION_CATEGORY.NEW_CHAT_MESSAGE]:
    NOTIFICATION_EVENT_TYPE.new_chat_message,
  [NOTIFICATION_CATEGORY.SUBSCRIPTION_EXPIRING]:
    NOTIFICATION_EVENT_TYPE.subscription_expiring,
  [NOTIFICATION_CATEGORY.SUBSCRIPTION_EXPIRED]:
    NOTIFICATION_EVENT_TYPE.subscription_expired,
  [NOTIFICATION_CATEGORY.PAYMENT_SUCCESS]:
    NOTIFICATION_EVENT_TYPE.payment_success,
  [NOTIFICATION_CATEGORY.PAYMENT_FAILED]:
    NOTIFICATION_EVENT_TYPE.payment_failed,
  [NOTIFICATION_CATEGORY.VERIFICATION_APPROVED]:
    NOTIFICATION_EVENT_TYPE.verification_approved,
  [NOTIFICATION_CATEGORY.VERIFICATION_REJECTED]:
    NOTIFICATION_EVENT_TYPE.verification_rejected,
  [NOTIFICATION_CATEGORY.ADMIN_NEW_VERIFICATION]:
    NOTIFICATION_EVENT_TYPE.admin_new_verification,
  [NOTIFICATION_CATEGORY.ADMIN_NEW_REPORT]:
    NOTIFICATION_EVENT_TYPE.admin_new_report,
  [NOTIFICATION_CATEGORY.ADMIN_NEW_USER]:
    NOTIFICATION_EVENT_TYPE.admin_new_user,
  [NOTIFICATION_CATEGORY.ADMIN_NEW_MASTER]:
    NOTIFICATION_EVENT_TYPE.admin_new_master,
  [NOTIFICATION_CATEGORY.ADMIN_SYSTEM_ALERT]:
    NOTIFICATION_EVENT_TYPE.admin_system_alert,
  [NOTIFICATION_CATEGORY.ADMIN_NEW_LEAD]:
    NOTIFICATION_EVENT_TYPE.admin_new_lead,
  [NOTIFICATION_CATEGORY.ADMIN_NEW_REVIEW]:
    NOTIFICATION_EVENT_TYPE.admin_new_review,
  [NOTIFICATION_CATEGORY.ADMIN_NEW_PAYMENT]:
    NOTIFICATION_EVENT_TYPE.admin_new_payment,
  [NOTIFICATION_CATEGORY.MASTER_RESPONDED]:
    NOTIFICATION_EVENT_TYPE.master_responded,
  [NOTIFICATION_CATEGORY.MASTER_AVAILABLE]:
    NOTIFICATION_EVENT_TYPE.master_available,
  [NOTIFICATION_CATEGORY.BOOKING_PENDING]:
    NOTIFICATION_EVENT_TYPE.booking_pending,
  [NOTIFICATION_CATEGORY.BOOKING_CONFIRMED]:
    NOTIFICATION_EVENT_TYPE.booking_confirmed,
  [NOTIFICATION_CATEGORY.BOOKING_CANCELLED]:
    NOTIFICATION_EVENT_TYPE.booking_cancelled,
  /** UI как у подтверждённого бронирования (напоминание) */
  [NOTIFICATION_CATEGORY.BOOKING_REMINDER]:
    NOTIFICATION_EVENT_TYPE.booking_confirmed,
  [NOTIFICATION_CATEGORY.NEW_PROMOTION]: NOTIFICATION_EVENT_TYPE.master_available,
  [NOTIFICATION_CATEGORY.PROMOTION_STARTED]:
    NOTIFICATION_EVENT_TYPE.master_available,
  [NOTIFICATION_CATEGORY.SYSTEM_MAINTENANCE]:
    NOTIFICATION_EVENT_TYPE.system_maintenance,
  [NOTIFICATION_CATEGORY.SYSTEM_UPDATE]:
    NOTIFICATION_EVENT_TYPE.system_update,
};
